sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
      - libssl-dev
rust:
  - stable
  - beta
  - nightly

script:
  - cargo test

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
